config:
  target: 'http://localhost'
  http:
    tls:
      rejectUnauthorized: false
  phases:
    - duration: 10800
      arrivalRate: 100
  processor: "./functions.js"
  defaults:
    headers:
      VGS-Client: 'artillery'
      Content-Type: 'application/json'
scenarios:
  - flow:
    - post:
        url: "http://127.0.0.1:8080/"
        beforeRequest: "beforeRequest"
        afterResponse: "afterResponse"
