config:
  target: 'http://localhost'
  phases:
    - duration: 10800
      arrivalRate: 100
  processor: "./functions.js"
scenarios:
  - flow:
    - post:
        url: "http://127.0.0.1:8080/"
        beforeRequest: "beforeRequest"
        afterResponse: "afterResponse"
